export const users = [
  {
    id: 1,
    fullname: "fulllala",
    username: "lala",
    password: "lili",
    email: "lala@gmail.com",
    gender: "Female",
    address: "Tambora",
    phone: "0123456789",
    status: "user",
    booking: [],
  },
  {
    id: 2,
    fullname: "owner",
    username: "owner",
    password: "owner",
    email: "owner@gmail.com",
    gender: "Male",
    address: "Kemang",
    phone: "0123456789",
    status: "owner",
    booking: [],
  },
];
